# Generated by Django 6.0.5 on 2026-05-17 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_movie', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('storyline', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
